start_slideshow:
  name: Start Slideshow
  description: Start a photo slideshow on a media player.
  fields:
    entity_id:
      name: Media player
      description: The media player to display the slideshow.
      required: true
      selector:
        entity:
          domain: media_player
    folder:
      name: Photo folder
      description: Path to the folder containing photos (should always start with /media).
      required: true
      default: /media
      selector:
        text: {}
    interval:
      name: Interval
      description: Time interval between photos. Too short (<5s) may cause issues.
      required: true
      default:
        hours: 0
        minutes: 0
        seconds: 5
      selector:
        duration: {}
    max_runtime:
      name: Max Runtime
      description: Maximum duration before automatically stopping the slideshow.
      required: true
      default:
        hours: 12
        minutes: 0
        seconds: 0
      selector:
        duration: {}
    shuffle:
      name: Shuffle photos
      description: If true, photos are randomly ordered each loop; set to false for alphabetical order.
      required: false
      default: true
      selector:
        boolean: {}
    recursive:
      name: Include subfolders
      description: If true, includes all subfolders under the main photo folder.
      required: false
      default: true
      selector:
        boolean: {}
    sort_folder_by_folder:
      name: Folder-by-Folder Sorting (works only when Shuffle is false)
      description: |
        If true, sorts files alphabetically within each folder (folder-by-folder).
        If false, sorts all files alphabetically regardless of folder structure.
      required: false
      default: true
      selector:
        boolean: {}
    sort_order:
      name: Sort Order (works only when Shuffle is false)
      description: Choose alphabetical, from newest to oldest or from oldest to newest sort order.
      selector:
        select:
          options:
            - alpha
            - newest
            - oldest
      default: alpha
    resume:
      name: Resume from Last Photo (works only when Shuffle is false)
      description: |
        If true, slideshow continues from where it was last stopped.
        If false, slideshow starts from the beginning.
      required: false
      default: true
      selector:
        boolean: {}
    loop:
      name: Loop slideshow
      description: If true, slideshow repeats indefinitely until stopped or max runtime is reached.
      required: false
      default: true
      selector:
        boolean: {}
    force:
      name: Force run
      description: If true, starts and runs even if media player is busy with other media.
      required: false
      default: true
      selector:
        boolean: {}
    sync_group:
      name: Sync Group
      description: >
        Optional name for a sync group. The first slideshow started becomes the owner.
        Other devices join as watchers and follow the owner's settings to stay in sync.
        Leave empty for no group
      required: false
      default: ""
      selector:
        text: {}

stop_slideshow:
  name: Stop Slideshow
  description: Stop the active slideshow on a media player.
  fields:
    entity_id:
      name: Media player
      description: The media player to stop the slideshow on.
      required: true
      selector:
        entity:
          domain: media_player
    turn_off:
      name: Turn Off Player
      description: If true, powers off the media player after stopping the slideshow. Set false to keep it on.
      required: false
      default: true
      selector:
        boolean: {}

reset_resume:
  name: Reset Resume Index
  description: Reset resume index for selected media player. If not specified, resume index will be reset for all devices.
  fields:
    entity_id:
      name: Media Player
      description: Media player to reset the resume index for.
      required: true
      selector:
        entity:
          domain: media_player

photo_of_the_day:
  name: Photo of the day
  description: Display random photo from the folder.
  fields:
    entity_id:
      name: Media player
      description: The media player to display the slideshow.
      required: true
      selector:
        entity:
          domain: media_player
    folder:
      name: Photo folder
      description: Path to the folder containing photos (should always start with /media).
      required: true
      default: /media
      selector:
        text: {}
    max_runtime:
      name: Max Runtime
      description: Maximum duration before automatically stopping the photo.
      required: true
      default:
        hours: 1
        minutes: 0
        seconds: 0
      selector:
        duration: {}
    recursive:
      name: Include subfolders
      description: If true, includes all subfolders under the main photo folder.
      required: false
      default: true
      selector:
        boolean: {}
    force:
      name: Force run
      description: If true, starts and runs even if media player is busy with other media.
      required: false
      default: true
      selector:
        boolean: {}

start_webslideshow:
  name: Start Web Slideshow
  description: Start a slideshow accessible in your browser (no media player required).
  fields:
    folder:
      name: Photo folder
      description: Path to the folder containing photos (should start with /media).
      required: true
      default: /media
      selector:
        text: {}
    interval:
      name: Interval
      description: Interval between photos in seconds.
      required: true
      default: 5
      selector:
        number:
          min: 1
          max: 3600
          mode: box
          unit_of_measurement: s
    shuffle:
      name: Shuffle photos
      description: If true, the slideshow will display photos in random order.
      required: false
      default: true
      selector:
        boolean: {}
    sort_folder_by_folder:
      name: Folder-by-Folder Sorting (only works when Shuffle=false)
      description: If true, photos will be sorted folder by folder instead of alphabetically in a single list.
      required: false
      default: true
      selector:
        boolean: {}
    recursive:
      name: Include subfolders
      description: If true, includes all subfolders under the main photo folder.
      required: false
      default: true
      selector:
        boolean: {}
    loop:
      name: Loop slideshow
      description: If true, the slideshow will loop endlessly. If false, it stops after showing all photos once.
      required: false
      default: true
      selector:
        boolean: {}
    auto_restart:
      name: Auto-Restart Slideshow
      description: >
          If true, the slideshow will automatically restart if it stops unexpectedly (useful for kiosk setups).
          This only runs a background watchdog task while Home Assistant is running (won't survive HA restart).
      required: false
      default: false
      selector:
        boolean: {}

stop_webslideshow:
  name: Stop Web Slideshow
  description: Stop the currently active web slideshow and cancel any optional auto-restart watchdog.

resume_slideshow:
  name: Resume Slideshow
  description: Resume the paused slideshow on a media player.
  fields:
    entity_id:
      name: Media player
      description: The media player to resume the slideshow on.
      required: true
      selector:
        entity:
          domain: media_player

pause_slideshow:
  name: Pause Slideshow
  description: Pause slideshow on a media player.
  fields:
    entity_id:
      name: Media player
      description: The media player to pause the slideshow on.
      required: true
      selector:
        entity:
          domain: media_player
